apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-cicd-demo
  labels:
    app: jenkins-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-cicd-demo
  template:
    metadata:
      labels:
        app: jenkins-cicd-demo
    spec:
      containers:
      - name: app
        image: ogembog/jenkins-cicd-demo:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-cicd-demo-service
spec:
  selector:
    app: jenkins-cicd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer